polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'

urlpatterns = [
	# ex: /polls/
    #url(r'^$', views.index, name='index'),
    url(r'^$', views.IndexView.as_view(), name='index'),

    # ex: /polls/5/
    # the 'name' value as called by the {$ url $} template tag
    #url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # ex: /polls/5/results/
	#url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
	url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),

    # ex: /polls/5/vote/
	url(r'^(?P<ballot_id>[0-9]+)/vote/$', views.vote, name='vote'),

]

sweng500BVS/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

polls/models.py
from __future__ import unicode_literals


from django.db import models
#from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone
import datetime
# Create your models here.


class Ballot(models.Model):
	ballot_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	end_date = models.DateTimeField('end date')
	def __str__(self):
		return self.ballot_text

	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
	ballot = models.ForeignKey(Ballot, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	choice_address = models.CharField(max_length=36)
	votes = models.IntegerField(default=0)
	
	def __str__(self):
		return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.urls import reverse
from django.template import loader
from django.shortcuts import render
from .models import Ballot, Choice
from django.views import generic



# Create your views here.

def vote(request, ballot_id):
	#return HttpResponse("You're voting on ballot %s" % ballot_id)
	ballot = get_object_or_404(Ballot, pk=ballot_id)

	try:
		selected_choice = ballot.choice_set.get(pk=request.POST['choice'])

	except (KeyError, Choice.DoesNotExist):
		# Redisplay the ballot voting form
		return render(request, 'polls/detail.html', 
			{ 'ballot': ballot, 'error_message': "You didn't select a choice.",})
	else:
		selected_choice.votes += 1
		selected_choice.save()

		# Always return an HTTPResponseRedirect after successfully dealing 
		# with POST data. This prevents data from being posted twice if a
		# user hits the back button.

		return HttpResponseRedirect(reverse('polls:results', args=(ballot.id,)))


class IndexView(generic.ListView):
	template_name = 'polls/index.html'
	context_object_name = 'latest_ballot_list'

	def get_queryset(self):
		"""Return the last five published ballot"""
		return Ballot.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
	model = Ballot
	template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
	model = Ballot
	template_name = 'polls/results.html'
	

polls/templates/polls/detail.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
		<link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
		<link rel="stylesheet" href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.css' %}">
		<link rel="stylesheet" href="{% static 'bootstrap-3.3.7-dist/css/bootstrap-theme.css' %}">
		<link rel="script" href="{% static 'bootstrap-3.3.7-dist/js/bootstrap.js' %}">
		<link rel="stylesheet" href="{% static 'css/polls.css' %}">
		{# Load the tag library #}
		{% load bootstrap3 %}

		{# Load CSS and JavaScript #}
		{% bootstrap_css %}
		{% bootstrap_javascript %}

		{# Display django.contrib.messages as Bootstrap alerts #}
		{% bootstrap_messages %}

		

	</head>
	<body>

		

	<div class="page-header">


		{% buttons %}
			<a href="{% url 'polls:index' %}" type="btn" class="btn btn-primary">{% bootstrap_icon "home" %}</a>
  		{% endbuttons %}

		<h1>{{ ballot.ballot_text }}</h1>
		<small>Select a ballot candidate:</small>


	</div>
	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


	<form action="{% url 'polls:vote' ballot.id %}" method="post">

	{% csrf_token %}
	{% for choice in ballot.choice_set.all %}
		<input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{ choice.id }}" />
		<label for="choice{{ forloop.counter }}" > {{ choice.choice_text }}</label>
		<!-- Display/Hide Counterparty Address -->
		<br />
		<small for="choice{{ forloop.counter }}" > Bitcoin Address: {{ choice.choice_address }}</small>
		<br />

		{% endfor %}


	<!-- Single button -->
		<div class="btn-group">
		  <button type="button submit" value="Vote" class="btn btn-danger">Vote</button>
		</div>

		<br />
		<br />


		<div class="btn-group btn-group-justified" role="group" aria-label="...">
		  <div class="btn-group" role="group">
			  	<a href="{% url 'polls:index' %}" type="btn" class="btn btn-default">Go Back</a>
		  </div>
		  <div class="btn-group" role="group">
		    <button type="button" class="btn btn-default">Previous Ballot</button>
		  </div>
		  <div class="btn-group" role="group">
		 
		  </div>
		</div>

	</body>

	<div class="page-footer">

	</div>

	</form>
</html>


<!--<ul>
{% for choice in ballot.choice_set.all %}
	<li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>
-->

polls/templates/polls/index.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<div class="container-fluid">
  

	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
		<link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
		<link rel="stylesheet" href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.css' %}">
		<link rel="stylesheet" href="{% static 'bootstrap-3.3.7-dist/css/bootstrap-theme.css' %}">
		<link rel="script" href="{% static 'bootstrap-3.3.7-dist/js/bootstrap.js' %}">
		<link rel="stylesheet" href="{% static 'css/polls.css' %}">

		{# Load the tag library #}
		{% load bootstrap3 %}

		{# Load CSS and JavaScript #}
		{% bootstrap_css %}
		{% bootstrap_javascript %}

		{# Display django.contrib.messages as Bootstrap alerts #}
		{% bootstrap_messages %}
	</head>

  {% buttons %}
  	<a href="{% url 'polls:index' %}" type="btn" class="btn btn-primary">{% bootstrap_icon "home" %}</a>
 
    <button type="submit" class="btn btn-primary">
      {% bootstrap_icon "info-sign" %} 
    </button>

	<a href="{% url 'admin:index' %}" type="btn" class="btn btn-primary">{% bootstrap_icon "user" %} Admin Login</a>

     <button type="submit" class="btn btn-primary">
      {% bootstrap_icon "user" %} User Login
    </button>


  {% endbuttons %}


<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
  		<h1> Ballots </h1>
		<h1> {{ ballot.ballot_text }}</h1>
		<small>Select a Ballot:</small>
  </div>
 <div class="col-md-4"></div> 
</div>
	{% if latest_ballot_list %}
		<ul>
		{% for ballot in latest_ballot_list %}
			<li><a href="{% url 'polls:detail' ballot.id %}"> {{ ballot.ballot_text }}</a></li>
			{% endfor %}
		</ul>
	{% else %}
		<p>No polls area available.</p>
	{% endif %}


</html>

polls/templates/polls/results.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
		<link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
		<link rel="stylesheet" href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.css' %}">
		<link rel="stylesheet" href="{% static 'bootstrap-3.3.7-dist/css/bootstrap-theme.css' %}">
		<link rel="script" href="{% static 'bootstrap-3.3.7-dist/js/bootstrap.js' %}">
		<link rel="stylesheet" href="{% static 'css/polls.css' %}">
		{# Load the tag library #}
		{% load bootstrap3 %}

		{# Load CSS and JavaScript #}
		{% bootstrap_css %}
		{% bootstrap_javascript %}

		{# Display django.contrib.messages as Bootstrap alerts #}
		{% bootstrap_messages %}
	</head>
	<div class="page-header">
		{% buttons %}
			<a href="{% url 'polls:index' %}" type="btn" class="btn btn-primary">{% bootstrap_icon "home" %}</a>
  		{% endbuttons %}
		<h1> {{ ballot.ballot_text }}</h1>
		<small>Vote Tally</small>
	</div>
	<ul>
		 {% for choice in ballot.choice_set.all %}

		 	<li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }} </li>
		 {% endfor %}
	</ul>

	<a href="{% url 'polls:detail' ballot.id %} ">Vote again?</a>
</html>